web:
  container_name: performance_no_front
  image: nginx
  volumes:
   - ./site:/usr/share/nginx/html/site
   - ./dist:/usr/share/nginx/html/dist
   - ./workshop-performance.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "3030:3030"
   - "2020:2020"
  command: /bin/bash -c "nginx -g 'daemon off;'"